# Generated by Django 4.2.3 on 2023-08-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Опубликован', 'Опубликован'), ('Неопубликован', 'Неопубликован')], default='Опубликован', max_length=200, verbose_name='Статус публикации'),
        ),
    ]
