# Generated by Django 4.2.3 on 2023-08-02 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_likes_short_savedposts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='short',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='short',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='short',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_post/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='short',
            name='views_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
