# Generated by Django 4.2.3 on 2023-08-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_profile_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscriber',
            new_name='subscribers',
        ),
    ]
